# Generated by Django 5.1.3 on 2025-02-14 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='leida',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='receta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.receta'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='usuario_receta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
