# Generated by Django 5.1.3 on 2025-02-14 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_notificacion_leida_alter_notificacion_receta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacion',
            name='usuario_receta',
        ),
    ]
