# Generated by Django 5.1.3 on 2025-02-14 20:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_remove_notificacion_usuario_receta'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='comentario',
            name='leida',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Notificacion',
        ),
    ]
